In [4]:
#Exploratory data analysis packages
import pandas as pd
import numpy as np
import random

# Machine Learning Packages
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [5]:
dataset=pd.read_csv("dataset25k.csv")

In [6]:
dataset.columns

Index(['Unnamed: 0', 'url', 'label'], dtype='object')

In [7]:
#Check for any missing data. If the output is not 0 then there is a value missing in the data set
dataset.isnull().sum().sum()

0

In [8]:
dataset_copy=dataset

In [9]:
dataset_copy.describe(include="all")

Unnamed: 0                           url         label
count   25000.000000                         25000  25000.000000
unique           NaN                         24892           NaN
top              NaN  http://ak.imgfarm.com/images           NaN
freq             NaN                            40           NaN
mean    12499.500000                           NaN      0.054520
std      7217.022701                           NaN      0.227045
min         0.000000                           NaN      0.000000
25%      6249.750000                           NaN      0.000000
50%     12499.500000                           NaN      0.000000
75%     18749.250000                           NaN      0.000000
max     24999.000000                           NaN      1.000000

In [10]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
# unnamed_cat = le.fit_transform(dataset.Unnamed: 0)
url_cat = le.fit_transform(dataset.url)
# label_cat   = le.fit_transform(dataset.label)

In [11]:
dataset_copy["url_cat"]=url_cat

In [12]:
dummy_fields=["url"]
dataset_copy=dataset_copy.drop(dummy_fields,axis=1)

In [13]:
dataset_copy.head(5)

Unnamed: 0  label  url_cat
0           0      1    10659
1           1      1    10182
2           2      1    10885
3           3      1    10886
4           4      1    11006

In [14]:
features =dataset_copy.values[:,:2]
target = dataset_copy.values[:,2]
features_train, features_test, target_train, target_test = train_test_split(features,
                                                                            target, test_size = 0.33, random_state = 32)

In [15]:
import time
start_train=time.time()

In [16]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(features_train, target_train)
# target_pred = clf.predict(features_test)

GaussianNB(priors=None, var_smoothing=1e-09)

In [17]:
end_train=time.time()
print("Time to Train : ",end_train-start_train)

Time to Train :  1.3431189060211182


In [18]:
start_test=time.time()

In [19]:
print("Accuracy ",clf.score(features_test, target_test)*100,"%")

Accuracy  0.3515151515151515 %


In [20]:
print("Accuracy ",clf.score(features_train, target_train)*100,"%")

Accuracy  99.97014925373135 %


In [21]:
end_test=time.time()
print("Time to Test : ",end_test-start_test)

Time to Test :  23.046238660812378


In [22]:
from sklearn.metrics import confusion_matrix
predicted = clf.predict(features_test)
matrix = confusion_matrix(target_test,predicted)
print(matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
# from sklearn.metrics import classification_report

# report = classification_report(target_test, predicted)
# print(report)

In [24]:
# # Visualization Packages
# import matplotlib.pyplot as plt
# import seaborn as sns

# # Confusion Matrix Graph With Seaborn
# sns.heatmap(matrix,annot=True)
# plt.show()